language: node_js
node_js:
  - '6'
env:
  - NODE_ENV=test

before_script:
  - npm install -g mocha

script:
  - npm run test

notifications:
  email:
    recipients:
      - 171721553@qq.com
    on_success: never # default: change
    on_failure: always # default: always
